version: 2
jobs:
  build:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      - run:
          name: install apk dependencies
          command: apt-get install -y libz-dev
      - run:
          name: install dependencies
          command: nimble install -y
      - run:
          name: build
          command: nim c nimrdkafka.nim
  build_alpine:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim:alpine
    steps:
      - checkout
      - run:
          name: install apk dependencies
          command: apk add zlib-dev
      - run:
          name: install dependencies
          command: nimble install -y
      - run:
          name: build
          command: nim c nimrdkafka.nim
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build_alpine
